import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/keybinds.toml"
]

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
  [window.dimensions]
  columns = 115
  lines = 20

  [window.padding]
  x = 20
  y = 20

[cursor]
  [cursor.style]
  shape = "Block"
