[colors]
  [colors.primary]
    background = "#090d10"
    foreground = "#dfc1af"

  [colors.normal]
    black   = "#090d10"
    red     = "#374B55"
    green   = "#3E5561"
    yellow  = "#5F5352"
    blue    = "#455A64"
    magenta = "#536872"
    cyan    = "#9A6C5C"
    white   = "#dfc1af"

  [colors.bright]
    black   = "#9c877a"
    red     = "#374B55"
    green   = "#3E5561"
    yellow  = "#5F5352"
    blue    = "#455A64"
    magenta = "#536872"
    cyan    = "#9A6C5C"
    white   = "#dfc1af"

